"""Render a status/index model as Markdown, JSON, HTML, or a shields badge.

Each function takes an already-built model dict (see docassert.status.derive)
and returns a string; none touch the document graph.
"""
from __future__ import annotations

import html as _h
import json


def esc(s):
    return _h.escape(str(s))


_EMOJI = {"green": "🟢", "amber": "🟠", "red": "🔴"}


def render_markdown(model, summary: bool = False) -> str:
    rag = model["rag"]
    c = model["counts"]
    title = model.get("title", "Project Status")
    heading = ("## " if summary else "# ") + title
    out = [f"{heading} — {_EMOJI[rag]} {rag.upper()}", ""]
    out.append(f"_Derived from {c['total']} documents across {c['kinds']} kinds "
               f"({c['approved']} approved). Generated by `docassert status` — do not edit._")
    out += ["", "## Signals", ""]

    for cov in model["coverage"]:
        pct = round(100 * cov["covered"] / cov["total"]) if cov["total"] else 100
        mark = "🟢" if not cov["gaps"] else "🟠"
        detail = f" — gaps: {', '.join(cov['gaps'])}" if cov["gaps"] else ""
        out.append(f"- {mark} **{cov['label']}**: {cov['covered']}/{cov['total']} ({pct}%){detail}")

    comp = model.get("completeness")
    if comp and comp.get("unknown"):
        out.append(f"- 🟠 **Profile** `{comp['profile']}` not found under profiles/")
    elif comp:
        mark = "🔴" if comp["blocks"] else (
            "🟠" if (comp["missing_required"] or comp["incomplete_required"]) else "🟢")
        if comp["missing_required"]:
            detail = f" — missing: {', '.join(comp['missing_required'])}"
        elif comp["incomplete_required"]:
            detail = f" — incomplete: {', '.join(comp['incomplete_required'])}"
        else:
            detail = ""
        out.append(f"- {mark} **Required documents** ({comp['profile']}): "
                   f"{comp['required_complete']}/{comp['required_total']} complete{detail}")

    if model["broken_references"]:
        out.append(f"- 🔴 **Broken references**: {len(model['broken_references'])} "
                   f"({', '.join(model['broken_references'][:3])}…)")
    failing = [d["id"] for d in model["documents"] if not d["passing"]]
    if failing:
        out.append(f"- 🔴 **Documents failing audit**: {', '.join(failing)}")

    for o in model.get("operations", []):
        mark = "🟢" if o["fresh"] else "🟠"
        verb = "next" if o["fresh"] else "OVERDUE since"
        out.append(f"- {mark} **Operations review** (`{o['id']}`): {verb} {o['review_by']}")
    if model["risks"]:
        open_r = [r for r in model["risks"] if r.get("disposition", "open") == "open"]
        rest = len(model["risks"]) - len(open_r)
        mark = "🟠" if open_r else "🟢"
        out.append(f"- {mark} **Open risks**: {len(open_r)}"
                   + (f" ({rest} dispositioned)" if rest else ""))
        for r in open_r[:5]:
            out.append(f"    - `{r['id']}` — {r['probability']}/{r['impact']} · owner: {r['owner']}")

    lr = model["latest_report"]
    if lr:
        out.append(f"- ℹ️ Latest status report `{lr['id']}` ({lr['period']}) reported **{lr['rag']}**")

    if not summary:
        out += ["", "## Documents", "", "| Kind | ID | Status | Audit |", "|---|---|---|---|"]
        for d in sorted(model["documents"], key=lambda x: (x["kind"], x["id"])):
            out.append(f"| {d['kind']} | {d['id']} | {d['status']} | {'✓' if d['passing'] else '✗'} |")
    else:
        out += ["", f"<sub>Full inventory of {c['total']} documents in "
                    "[`STATUS.md`](../../blob/main/STATUS.md).</sub>"]
    return "\n".join(out) + "\n"


def render_json(model) -> str:
    return json.dumps(model, indent=2) + "\n"


_HTML_CSS = """
  :root { --bg:#0d1117; --panel:#161b22; --border:#30363d; --ink:#e6edf3;
          --muted:#8b949e; --ok:#2ea043; --amber:#d29922; --bad:#f85149; }
  * { box-sizing:border-box; }
  body { margin:0; background:var(--bg); color:var(--ink);
         font:15px/1.5 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif; }
  main { max-width:860px; margin:0 auto; padding:40px 24px 64px; }
  header { display:flex; align-items:center; gap:16px; flex-wrap:wrap; margin-bottom:8px; }
  .rag { font-weight:700; font-size:13px; letter-spacing:.08em; color:#0d1117;
         padding:5px 12px; border-radius:999px; }
  h1 { font-size:26px; margin:0; }
  .meta { color:var(--muted); font-size:13px; margin:2px 0 30px; }
  section { margin-bottom:30px; }
  h2 { font-size:15px; text-transform:uppercase; letter-spacing:.05em;
       color:var(--muted); border-bottom:1px solid var(--border); padding-bottom:8px; }
  .sig { margin:12px 0; }
  .sig-h { display:flex; justify-content:space-between; font-size:14px; margin-bottom:5px; }
  .bar { height:8px; background:var(--border); border-radius:4px; overflow:hidden; }
  .bar-f { height:100%; background:var(--ok); border-radius:4px; }
  ul { padding-left:18px; } li { margin:4px 0; }
  code { font-family:ui-monospace,SFMono-Regular,Menlo,monospace; font-size:13px;
         background:#21262d; padding:1px 5px; border-radius:4px; }
  table { width:100%; border-collapse:collapse; font-size:13.5px; }
  th,td { text-align:left; padding:7px 10px; border-bottom:1px solid var(--border); }
  th { color:var(--muted); font-weight:600; }
  td.ok { color:var(--ok); } td.bad { color:var(--bad); font-weight:700; }
  footer { color:var(--muted); font-size:12px; margin-top:36px; border-top:1px solid var(--border); padding-top:14px; }
  .back { display:inline-block; color:var(--muted); text-decoration:none; font-size:13px; margin-bottom:14px; }
  .back:hover { color:var(--ink); }
"""

_INDEX_CSS = """
  .grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(260px,1fr)); gap:16px; }
  a.card { display:block; background:var(--panel); border:1px solid var(--border);
           border-radius:10px; padding:18px; text-decoration:none; color:var(--ink);
           transition:border-color .15s, transform .15s; }
  a.card:hover { border-color:var(--muted); transform:translateY(-2px); }
  .card-h { display:flex; align-items:center; gap:8px; margin-bottom:10px; }
  .dot { width:10px; height:10px; border-radius:50%; }
  .rag-t { font-size:12px; font-weight:700; letter-spacing:.06em; }
  .code { margin-left:auto; font:12px ui-monospace,SFMono-Regular,Menlo,monospace;
          background:#21262d; color:var(--muted); padding:2px 7px; border-radius:5px; }
  .name { font-size:16px; font-weight:600; margin-bottom:3px; }
  .card .pid { color:var(--muted); font-size:12px;
               font-family:ui-monospace,SFMono-Regular,Menlo,monospace; margin-bottom:8px; }
  .sponsor { font-size:13px; color:var(--muted); margin-bottom:10px; }
  .stats { font-size:12.5px; color:var(--muted); border-top:1px solid var(--border); padding-top:8px; }
"""


def render_html(model) -> str:
    import datetime
    rag = model["rag"]
    c = model["counts"]
    color = {"green": "var(--ok)", "amber": "var(--amber)", "red": "var(--bad)"}[rag]
    bar_color = {"green": "var(--ok)", "amber": "var(--amber)", "red": "var(--bad)"}[rag]

    coverage = "".join(
        f'<div class="sig"><div class="sig-h"><span>{esc(cov["label"])}</span>'
        f'<span>{cov["covered"]}/{cov["total"]}'
        + (f' · gaps: {esc(", ".join(cov["gaps"]))}' if cov["gaps"] else "")
        + '</span></div><div class="bar"><div class="bar-f" style="width:'
        f'{(100 * cov["covered"] // cov["total"]) if cov["total"] else 100}%'
        + (";background:var(--amber)" if cov["gaps"] else "") + '"></div></div></div>'
        for cov in model["coverage"])

    def sev(value):
        color = {"critical": "var(--bad)", "high": "var(--bad)",
                 "medium": "var(--amber)", "low": "var(--ok)"}.get(
                     value, "var(--muted)")
        return f'<td style="color:{color};font-weight:600;">{esc(value)}</td>'

    def disp(value):
        color = {"open": "var(--amber)", "mitigated": "var(--ok)",
                 "accepted": "var(--muted)", "closed": "var(--muted)"}.get(
                     value, "var(--amber)")
        return f'<td style="color:{color};font-weight:600;">{esc(value)}</td>'

    if model["risks"]:
        risk_rows = "".join(
            f'<tr><td><code>{esc(r["id"])}</code></td>'
            f'<td>{esc(r["description"])}</td>'
            f'<td>{", ".join(f"<code>{esc(b)}</code>" for b in r["threatens"]) or "—"}</td>'
            + sev(r["probability"]) + sev(r["impact"])
            + f'<td>{esc(r["owner"])}</td>'
            + disp(r.get("disposition", "open"))
            + f'<td>{esc(r["response"]) or "—"}</td></tr>'
            for r in model["risks"])
        risks = ('<table><thead><tr><th>ID</th><th>Risk</th><th>Threatens</th>'
                 '<th>Probability</th><th>Impact</th><th>Owner</th>'
                 '<th>Status</th><th>Response</th></tr></thead>'
                 f'<tbody>{risk_rows}</tbody></table>')
    else:
        risks = "<p>None open.</p>"

    ops_html = "".join(
        f'<div class="sig"><div class="sig-h"><span>Operations review · '
        f'<code>{esc(o["id"])}</code></span><span style="color:'
        + ("var(--ok)" if o["fresh"] else "var(--amber)") + ';font-weight:600;">'
        + ("next " if o["fresh"] else "overdue since ") + f'{esc(o["review_by"])}'
        '</span></div></div>'
        for o in model.get("operations", []))

    problems = ""
    if model["broken_references"]:
        problems += ("<section><h2>Broken references</h2><ul>"
                     + "".join(f"<li><code>{esc(b)}</code></li>" for b in model["broken_references"])
                     + "</ul></section>")
    failing = [d for d in model["documents"] if not d["passing"]]
    if failing:
        problems += ("<section><h2>Documents failing audit</h2><ul>"
                     + "".join(f'<li><code>{esc(d["id"])}</code></li>' for d in failing)
                     + "</ul></section>")

    rows = "".join(
        f'<tr><td>{esc(d["kind"])}</td><td><code>{esc(d["id"])}</code></td>'
        f'<td>{esc(d["status"])}</td>'
        f'<td class="{"ok" if d["passing"] else "bad"}">{"✓" if d["passing"] else "✗"}</td></tr>'
        for d in sorted(model["documents"], key=lambda x: (x["kind"], x["id"])))

    lr = model["latest_report"]
    report = (f'<code>{esc(lr["id"])}</code> ({esc(lr["period"])}) → reported <b>{esc(lr["rag"])}</b>'
              if lr else "None on record.")
    gen = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    comp = model.get("completeness")
    document_set = ""
    if comp and comp.get("unknown"):
        document_set = (f'<section><h2>Document set</h2><p style="color:var(--bad)">'
                        f'Profile <code>{esc(comp["profile"])}</code> not found under profiles/.</p></section>')
    elif comp:
        _st = {"complete": ("var(--ok)", "complete"),
               "incomplete": ("var(--amber)", "incomplete"),
               "missing": ("var(--bad)", "missing")}

        def _row(item, required):
            col, lab = _st[item["state"]]
            if item["state"] == "missing" and not required:
                col, lab = "var(--muted)", "not added"
            return (f'<tr><td><code>{esc(item["kind"])}</code></td>'
                    f'<td style="color:{col};font-weight:600;">{lab}</td></tr>')

        req_rows = "".join(_row(i, True) for i in comp["required"])
        rec_rows = "".join(_row(i, False) for i in comp["recommended"])
        sep = ('<tr><td colspan="2" style="color:var(--muted);border:0;padding:14px 10px 4px;'
               'font-size:11px;text-transform:uppercase;letter-spacing:.05em;">Recommended</td></tr>'
               if rec_rows else "")
        if comp["blocks"]:
            note = (f'<p style="color:var(--bad);font-size:13px;margin:0 0 10px;">Missing required: '
                    f'<code>{esc(", ".join(comp["missing_required"]))}</code> — blocks release '
                    f'while <code>{esc(comp["enforce_when"])}</code>.</p>')
        elif comp["missing_required"] or comp["incomplete_required"]:
            note = (f'<p style="color:var(--amber);font-size:13px;margin:0 0 10px;">Advisory until '
                    f'the project is <code>{esc(comp["enforce_when"])}</code>.</p>')
        else:
            note = ""
        document_set = (f'<section><h2>Document set · {esc(comp["profile"])} '
                        f'({comp["required_complete"]}/{comp["required_total"]} required complete)</h2>'
                        f'{note}<table><thead><tr><th>Kind</th><th>State</th></tr></thead>'
                        f'<tbody>{req_rows}{sep}{rec_rows}</tbody></table></section>')

    execution_html = ""
    ex = model.get("execution")
    if ex:
        feat_rows: list[str] = []
        for f in ex.get("features", []):
            total = f.get("stories_total", 0) or 0
            done = f.get("stories_closed", 0) or 0
            pct = (100 * done // total) if total else 0
            mark = "✓" if f.get("closed") else ""
            issue = f' · <a href="https://github.com/{esc(ex.get("repo", ""))}/issues/{f["issue"]}">#{f["issue"]}</a>' if f.get("issue") else ""
            feat_rows.append(
                f'<div class="sig"><div class="sig-h"><span>{esc(f["id"])} {mark}</span>'
                f'<span>{done}/{total} stories{issue}</span></div>'
                f'<div class="bar"><div class="bar-f" style="width:{pct}%;background:var(--ok)"></div></div></div>')
        overall_t = ex.get("stories_total", 0) or 0
        overall_d = ex.get("stories_closed", 0) or 0
        execution_html = (
            f'<section><h2>Delivery · {overall_d}/{overall_t} stories closed</h2>'
            '<p style="color:var(--muted);font-size:13px;margin:0 0 10px">'
            "Read from the bridge-managed issues. Scope lives in these documents; "
            "delivery lives on the board.</p>" + "".join(feat_rows) + "</section>")
        scope = ex.get("scope") or {}
        bad = scope.get("unverified", []) + scope.get("orphaned", [])
        if bad:
            items = "".join(
                f'<li><a href="https://github.com/{esc(i.get("repo") or ex.get("repo") or "")}/issues/{i["number"]}">#{i["number"]}</a> {esc(i["title"])}</li>'
                for i in bad)
            execution_html += (
                f'<section><h2 style="color:var(--bad)">Scope · {len(bad)} unmatched item(s)</h2>'
                f'<ul>{items}</ul></section>')
        else:
            execution_html += ('<section><h2>Scope</h2><p style="color:var(--ok)">'
                               "Every open issue matches an approved item in the documents.</p></section>")

    title = esc(model.get("title", "Project Status"))
    pid = model.get("project")
    back = '<a class="back" href="index.html">← all projects</a>' if pid else ""
    scope = f" · <code>{esc(pid)}</code>" if pid else ""

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title} — {rag.upper()}</title>
<style>{_HTML_CSS}
  .bar-f {{ background:{bar_color}; }}</style></head>
<body><main>
  {back}
  <header>
    <span class="rag" style="background:{color}">{rag.upper()}</span>
    <h1>{title}</h1>
  </header>
  <p class="meta">Derived from {c['total']} documents · {c['kinds']} kinds ·
    {c['approved']} approved{scope} · generated {gen}. Do not edit — regenerated from the documents.</p>
  <section><h2>Traceability coverage</h2>{coverage}{ops_html}</section>
  {document_set}
  {execution_html}
  {problems}
  <section><h2>Risks ({len([r for r in model['risks'] if r.get('disposition', 'open') == 'open'])} open of {len(model['risks'])})</h2>{risks}</section>
  <section><h2>Latest status report</h2><p>{report}</p></section>
  <section><h2>Documents ({c['total']})</h2>
    <table><thead><tr><th>Kind</th><th>ID</th><th>Status</th><th>Audit</th></tr></thead>
    <tbody>{rows}</tbody></table></section>
  <footer>Generated by <code>docassert status</code> from the documents in this repository.</footer>
</main></body></html>
"""


_RAG_COLOR = {"green": "var(--ok)", "amber": "var(--amber)", "red": "var(--bad)"}
_BADGE_COLOR = {"green": "brightgreen", "amber": "orange", "red": "red"}


def render_badge_json(rag: str, label: str = "pmo docs") -> str:
    """A shields.io endpoint payload (https://shields.io/badges/endpoint-badge),
    so a README can carry a live derived-status badge."""
    return json.dumps({"schemaVersion": 1, "label": label,
                       "message": rag, "color": _BADGE_COLOR[rag]}) + "\n"


def _index_card(p, esc) -> str:
    dot = _RAG_COLOR[p["rag"]]

    def plural(n, word):
        return f"{n} {word}" + ("s" if n != 1 else "")

    stats = [plural(p["total"], "doc")]
    comp = p.get("completeness")
    if comp and not comp.get("unknown"):
        stats.append(f'{comp["required_complete"]}/{comp["required_total"]} required')
    if p["risks"]:
        stats.append(plural(p["risks"], "open risk"))
    if p["coverage_gaps"]:
        stats.append(plural(p["coverage_gaps"], "coverage gap"))
    if p["failing"]:
        stats.append(plural(p["failing"], "failing doc"))
    if p["broken"]:
        stats.append(plural(p["broken"], "broken ref"))

    return (f'<a class="card" href="{esc(p["id"])}.html">'
            f'<div class="card-h"><span class="dot" style="background:{dot}"></span>'
            f'<span class="rag-t" style="color:{dot}">{esc(p["rag"].upper())}</span>'
            f'<span class="code">{esc(p["code"])}</span></div>'
            f'<div class="name">{esc(p["name"])}</div>'
            f'<div class="pid">{esc(p["id"])} · {esc(p["lifecycle"])}</div>'
            f'<div class="sponsor">Sponsor: {esc(p["sponsor"])}</div>'
            f'<div class="stats">{" · ".join(esc(s) for s in stats)}</div></a>')


def render_index_markdown(index) -> str:
    """A portfolio table: one row per project with its derived RAG."""
    overall = index["overall"]["rag"]
    out = [f"# Projects — {_EMOJI[overall]} {overall.upper()}", "",
           "| Project | Code | RAG | Docs | Required | Open risks | Sponsor |",
           "|---|---|---|---|---|---|---|"]
    for p in index["projects"]:
        comp = p.get("completeness")
        required = (f"{comp['required_complete']}/{comp['required_total']} ({comp['profile']})"
                    if comp and not comp.get("unknown") else "—")
        out.append(
            f"| {p['name']} | `{p['code']}` | {_EMOJI[p['rag']]} {p['rag'].upper()} "
            f"| {p['total']} | {required} | {p['risks']} | {p['sponsor']} |")
    return "\n".join(out) + "\n"


def render_index_html(index) -> str:
    """The multi-project landing page: one linked RAG card per project."""
    import datetime

    overall = index["overall"]["rag"]
    ocolor = _RAG_COLOR[overall]
    gen = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    cards = "".join(_index_card(p, esc) for p in index["projects"])
    n = len(index["projects"])

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>PMO as Code — Projects</title>
<style>{_HTML_CSS}{_INDEX_CSS}</style></head>
<body><main>
  <header>
    <span class="rag" style="background:{ocolor}">{overall.upper()}</span>
    <h1>Projects</h1>
  </header>
  <p class="meta">{n} project(s) · derived portfolio health · generated {gen}.
    Each card's RAG is computed from that project's own documents.</p>
  <section class="grid">{cards}</section>
  <footer>Generated by <code>docassert pages</code> from the documents in this repository.</footer>
</main></body></html>
"""
